name: simple-ping-visits

services:
  db:
    image: postgres:18.0
    environment: &postgres_env
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MCT
    restart: always

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      <<: *postgres_env
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: always
    ports:
      - "5000:8000"
