services:
  app:
    build: ./appdir
    env_file: "./env_vars.env"
    ports:
     - "5000:80"
    depends_on:
      db:
        condition: service_started
      init_db:
        condition: service_completed_successfully

  db:
    image: "postgres:18-alpine"
    env_file: "./env_vars.env"
    volumes:
     - ./pgdata:/var/lib/postgresql/18/docker # $PGDATA
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5

  init_db:
    build: ./appdir
    env_file: "./env_vars.env"
    command: ["python", "app/init_db.py"]
    restart: no
    depends_on:
      db:
        condition: service_healthy
  
  visits_cache:
    image: "redis:7-alpine"
