name: simple-ping-visits

services:
  db:
    image: postgres:18.0
    environment: &postgres_env
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MCT
    healthcheck:
      test: pg_isready --username=$${POSTGRES_USER} --dbname=$${POSTGRES_DB}
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 0s
    restart: always

  migration:
    build:
      context: .
      dockerfile: ./migration/Dockerfile
    environment: &postgres_db_env
      <<: *postgres_env
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  server:
    extends:
      file: docker-compose.dev.yaml
      service: server
    environment:
      <<: *postgres_db_env
      DEV: false
    depends_on:
      migration:
        condition: service_completed_successfully

  nginx:
    image: nginx:1.29.3
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    depends_on:
      - server
    restart: always
