[project]
name = "mct-2025-containers"
version = "0.1.0"
description = ""
requires-python = ">=3.12, <4"
dependencies = [
    "fastapi[standard] (>=0.121, <0.122)",
    "psycopg[binary] (>=3.2.12,<4)",
    "sqlalchemy (>=2.0.44, <3)",
    "alembic (>=1.17.1, <2)",
    "pytest (>=9.0.0, <10)",
]
