[project]
name = "webserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "psycopg[binary]>=3.2.12",
    "sqlalchemy>=2.0.44",
]
